/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

public void rightClick(GButton source, GEvent event) { //_CODE_:rightButton:684602:
  //println("button1 - GButton >> GEvent." + event + " @ " + millis());
  port.write('d');
  println("Zumo is turning right");
} //_CODE_:rightButton:684602:

public void forwardClick(GButton source, GEvent event) { //_CODE_:forwardButton:880523:
  //println("button2 - GButton >> GEvent." + event + " @ " + millis());
  println("Zumo is going straight");
  port.write('w');
} //_CODE_:forwardButton:880523:

public void leftClick(GButton source, GEvent event) { //_CODE_:leftButton:555263:
  //println("button3 - GButton >> GEvent." + event + " @ " + millis());
  println("Zumo is turning left");
  port.write('a');
} //_CODE_:leftButton:555263:

public void roomRightClick(GButton source, GEvent event) { //_CODE_:roomRightButton:286345:
  //println("button4 - GButton >> GEvent." + event + " @ " + millis());
  println("Zumo STOPPED");
  port.write('r');
} //_CODE_:roomRightButton:286345:

public void downClick(GButton source, GEvent event) { //_CODE_:downButton:748030:
  //println("button6 - GButton >> GEvent." + event + " @ " + millis());
  println("Zumo is reversing");
  port.write('s');
} //_CODE_:downButton:748030:

public void consoleEvent(GTextArea source, GEvent event) { //_CODE_:consoleTextArea:321853:
  println("textarea1 - GTextArea >> GEvent." + event + " @ " + millis());
} //_CODE_:consoleTextArea:321853:

public void endClick(GButton source, GEvent event) { //_CODE_:endButton:304310:
  println("END");
  port.write('e');
} //_CODE_:endButton:304310:

public void startButtonClick(GButton source, GEvent event) { //_CODE_:startButton:510164:
  println("MOVE AUTONOMOUSLY");
  port.write('c');
} //_CODE_:startButton:510164:

public void caliberateClick(GButton source, GEvent event) { //_CODE_:Caliberate:256475:
  println("Caliberate - GButton >> GEvent." + event + " @ " + millis());
} //_CODE_:Caliberate:256475:

public void roomLeftClick(GButton source, GEvent event) { //_CODE_:roomLeftButton:860167:
  println("roomLeftButton - GButton >> GEvent." + event + " @ " + millis());
  port.write('f');
} //_CODE_:roomLeftButton:860167:

public void upperRightClick(GButton source, GEvent event) { //_CODE_:upperRightButton:396723:
  println("button1 - GButton >> GEvent." + event + " @ " + millis());
  port.write('d');
} //_CODE_:upperRightButton:396723:

public void upperLeftClick(GButton source, GEvent event) { //_CODE_:upperLeftButton:457349:
  println("button2 - GButton >> GEvent." + event + " @ " + millis());
  port.write('A');
} //_CODE_:upperLeftButton:457349:

public void goOutTheRoomClick(GButton source, GEvent event) { //_CODE_:goOutTheRoom:261424:
  println("goOutTheRoom - GButton >> GEvent." + event + " @ " + millis());
  port.write('n');
} //_CODE_:goOutTheRoom:261424:

public void goOutOfTheLeftRoomClick(GButton source, GEvent event) { //_CODE_:goOutOfTheLeftRoom:571898:
  println("goOutOfTheLeftRoom - GButton >> GEvent." + event + " @ " + millis());
  port.write('t');
} //_CODE_:goOutOfTheLeftRoom:571898:

public void reverseABitClick(GButton source, GEvent event) { //_CODE_:reverseABit:715412:
  println("reverseABit - GButton >> GEvent." + event + " @ " + millis());
  port.write('S');
} //_CODE_:reverseABit:715412:

public void forwardABitClick(GButton source, GEvent event) { //_CODE_:forwardABit:216060:
  println("forwardABit - GButton >> GEvent." + event + " @ " + millis());
  port.write('W');
} //_CODE_:forwardABit:216060:

public void reverseButtonClick(GButton source, GEvent event) { //_CODE_:reverseButton:440788:
  println("reverseButton - GButton >> GEvent." + event + " @ " + millis());
  port.write('s');
} //_CODE_:reverseButton:440788:

public void uTurnRightWingClick(GButton source, GEvent event) { //_CODE_:uTurnRightWing:228717:
  println("uTurnRightWing - GButton >> GEvent." + event + " @ " + millis());
  port.write('u');
} //_CODE_:uTurnRightWing:228717:

public void uTurnLeftWingCliick(GButton source, GEvent event) { //_CODE_:uTurnLeftWing:721119:
  println("uTurnLeftWing - GButton >> GEvent." + event + " @ " + millis());
  port.write('i');
} //_CODE_:uTurnLeftWing:721119:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setCursor(ARROW);
  surface.setTitle("Sketch Window");
  rightButton = new GButton(this, 199, 18, 80, 30);
  rightButton.setText("Turn Right");
  rightButton.addEventHandler(this, "rightClick");
  forwardButton = new GButton(this, 5, 19, 80, 30);
  forwardButton.setText("Forward");
  forwardButton.addEventHandler(this, "forwardClick");
  leftButton = new GButton(this, 298, 20, 80, 30);
  leftButton.setText("Turn Left");
  leftButton.addEventHandler(this, "leftClick");
  roomRightButton = new GButton(this, 119, 161, 80, 30);
  roomRightButton.setText("Room on The Right");
  roomRightButton.addEventHandler(this, "roomRightClick");
  downButton = new GButton(this, 105, 90, 80, 33);
  downButton.setText("Reverse");
  downButton.addEventHandler(this, "downClick");
  consoleTextArea = new GTextArea(this, 416, 72, 250, 277, G4P.SCROLLBARS_NONE);
  consoleTextArea.setOpaque(true);
  consoleTextArea.addEventHandler(this, "consoleEvent");
  zumoConsoleLabel = new GLabel(this, 417, 43, 156, 20);
  zumoConsoleLabel.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  zumoConsoleLabel.setText("ZUMO CONSOLE");
  zumoConsoleLabel.setOpaque(false);
  endButton = new GButton(this, 522, 369, 80, 30);
  endButton.setText("END");
  endButton.addEventHandler(this, "endClick");
  startButton = new GButton(this, 420, 369, 80, 30);
  startButton.setText("START");
  startButton.addEventHandler(this, "startButtonClick");
  Caliberate = new GButton(this, 1077, -22, 80, 30);
  Caliberate.setText("Caliberate");
  Caliberate.addEventHandler(this, "caliberateClick");
  roomLeftButton = new GButton(this, 20, 163, 80, 30);
  roomLeftButton.setText("Room on The Left");
  roomLeftButton.addEventHandler(this, "roomLeftClick");
  upperRightButton = new GButton(this, 201, 68, 80, 30);
  upperRightButton.setText("Upper Right");
  upperRightButton.addEventHandler(this, "upperRightClick");
  upperLeftButton = new GButton(this, 298, 67, 80, 30);
  upperLeftButton.setText("Upper Left");
  upperLeftButton.addEventHandler(this, "upperLeftClick");
  goOutTheRoom = new GButton(this, 117, 217, 80, 30);
  goOutTheRoom.setText("Go out of the right room");
  goOutTheRoom.addEventHandler(this, "goOutTheRoomClick");
  goOutOfTheLeftRoom = new GButton(this, 19, 217, 80, 30);
  goOutOfTheLeftRoom.setText("Go out of the left room");
  goOutOfTheLeftRoom.addEventHandler(this, "goOutOfTheLeftRoomClick");
  reverseABit = new GButton(this, 99, 69, 80, 30);
  reverseABit.setText("Reverse A Bit");
  reverseABit.addEventHandler(this, "reverseABitClick");
  forwardABit = new GButton(this, 4, 68, 80, 30);
  forwardABit.setText("Forward A Bit");
  forwardABit.addEventHandler(this, "forwardABitClick");
  reverseButton = new GButton(this, 98, 18, 80, 30);
  reverseButton.setText("Reverse");
  reverseButton.addEventHandler(this, "reverseButtonClick");
  uTurnRightWing = new GButton(this, 117, 273, 80, 30);
  uTurnRightWing.setText("U-Turn Right Wing");
  uTurnRightWing.addEventHandler(this, "uTurnRightWingClick");
  uTurnLeftWing = new GButton(this, 20, 276, 80, 30);
  uTurnLeftWing.setText("U-Turn Left Wing");
  uTurnLeftWing.addEventHandler(this, "uTurnLeftWingCliick");
}

// Variable declarations 
// autogenerated do not edit
GButton rightButton; 
GButton forwardButton; 
GButton leftButton; 
GButton roomRightButton; 
GButton downButton; 
GTextArea consoleTextArea; 
GLabel zumoConsoleLabel; 
GButton endButton; 
GButton startButton; 
GButton Caliberate; 
GButton roomLeftButton; 
GButton upperRightButton; 
GButton upperLeftButton; 
GButton goOutTheRoom; 
GButton goOutOfTheLeftRoom; 
GButton reverseABit; 
GButton forwardABit; 
GButton reverseButton; 
GButton uTurnRightWing; 
GButton uTurnLeftWing; 
